#!/usr/bin/env bash
# Author: Prof. Anis Koubaa <anis.koubaa@gmail.com>
# RAISE 2026 — hardware detection.
#
# Writes sim/.env with OS, CPU/RAM, GPU, and derived RAISE_HW_TIER.
# The .env file is sourceable by bash AND consumable by docker compose.
#
# Re-run any time hardware changes; this script is idempotent.

set -euo pipefail

SIM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${SIM_DIR}/.env"

# ── OS ─────────────────────────────────────────────────────────────────────
os_id=unknown
os_version=unknown
os_codename=unknown
is_wsl=0

if [[ -r /etc/os-release ]]; then
  # shellcheck disable=SC1091
  source /etc/os-release
  os_id="${ID:-unknown}"
  os_version="${VERSION_ID:-unknown}"
  os_codename="${VERSION_CODENAME:-unknown}"
fi

kernel="$(uname -r)"

if grep -qi microsoft /proc/version 2>/dev/null; then
  is_wsl=1
fi

# ── CPU / RAM ──────────────────────────────────────────────────────────────
cpu_cores="$(nproc)"
ram_kb="$(awk '/^MemTotal:/ {print $2}' /proc/meminfo)"
ram_gb=$(( (ram_kb + 524288) / 1048576 ))   # round to nearest GiB

# ── GPU (NVIDIA only — see note in sim/README.md for AMD/Intel) ────────────
has_gpu=0
gpu_vendor=
gpu_name=
gpu_vram_gb=0

if command -v nvidia-smi >/dev/null 2>&1; then
  if nvidia_out="$(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader,nounits 2>/dev/null)" \
     && [[ -n "$nvidia_out" ]]; then
    gpu_name="$(echo "$nvidia_out" | head -n1 | cut -d',' -f1 | xargs)"
    vram_mib="$(echo "$nvidia_out" | head -n1 | cut -d',' -f2 | xargs)"
    if [[ "$vram_mib" =~ ^[0-9]+$ ]]; then
      gpu_vram_gb=$(( (vram_mib + 512) / 1024 ))
      has_gpu=1
      gpu_vendor=nvidia
    fi
  fi
fi

# ── Tier classification ────────────────────────────────────────────────────
# CPU_ONLY  : no NVIDIA GPU, or VRAM < 6 GB (insufficient for local VLM)
# GPU_LOW   : NVIDIA GPU, 6 GB ≤ VRAM < 16 GB
# GPU_HIGH  : NVIDIA GPU, VRAM ≥ 16 GB
if (( has_gpu == 0 )) || (( gpu_vram_gb < 6 )); then
  tier=CPU_ONLY
  render_engine=ogre
elif (( gpu_vram_gb < 16 )); then
  tier=GPU_LOW
  render_engine=ogre2
else
  tier=GPU_HIGH
  render_engine=ogre2
fi

# VLA always defaults to remote; users on GPU_HIGH may flip to "local" by hand.
vla_backend=remote

# ── ROS 2 distro (derived from Ubuntu version) ─────────────────────────────
# Ubuntu 24.04 (Noble)  → Jazzy   — TESTED, the reference platform for RAISE 2026.
# Ubuntu 22.04 (Jammy)  → Humble  — UNTESTED, best-effort. Both run Gazebo
#                                   Harmonic so the labs/worlds are unchanged
#                                   (Humble pulls Harmonic via ros-humble-ros-gzharmonic
#                                   instead of its default Fortress pairing).
# anything else         → no native path; use Docker.
ros_distro=unsupported
native_supported=0
if [[ "$os_id" == "ubuntu" ]]; then
  case "$os_version" in
    24.04) ros_distro=jazzy  ; native_supported=1 ;;
    22.04) ros_distro=humble ; native_supported=1 ;;
  esac
fi

# ── Write .env ─────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# RAISE 2026 hardware profile — generated by sim/bootstrap/detect_hardware.sh
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Re-run detect_hardware.sh to regenerate. Manual edits will be overwritten.

# ── OS ───────────────────────────────────────────────────────────────────
RAISE_OS_ID=${os_id}
RAISE_OS_VERSION=${os_version}
RAISE_OS_CODENAME=${os_codename}
RAISE_KERNEL=${kernel}
RAISE_IS_WSL=${is_wsl}

# ── ROS 2 distro (derived from Ubuntu version) ───────────────────────────
# jazzy (24.04, TESTED) | humble (22.04, UNTESTED) | unsupported (use Docker)
RAISE_ROS_DISTRO=${ros_distro}
RAISE_NATIVE_SUPPORTED=${native_supported}

# ── CPU / memory ─────────────────────────────────────────────────────────
RAISE_CPU_CORES=${cpu_cores}
RAISE_RAM_GB=${ram_gb}

# ── GPU (NVIDIA detection only; AMD/Intel users may set renderer manually) ─
RAISE_HAS_GPU=${has_gpu}
RAISE_GPU_VENDOR=${gpu_vendor}
RAISE_GPU_NAME="${gpu_name}"
RAISE_GPU_VRAM_GB=${gpu_vram_gb}

# ── Tier (derived) ───────────────────────────────────────────────────────
RAISE_HW_TIER=${tier}

# ── Sim defaults (derived from tier) ─────────────────────────────────────
# RAISE_VLA_BACKEND: remote (default) | local
#   Switch to 'local' only if RAISE_HW_TIER=GPU_HIGH and you want self-hosted VLA.
RAISE_VLA_BACKEND=${vla_backend}
RAISE_VLA_ENDPOINT=https://TBD

# GZ_RENDER_ENGINE: ogre (Ogre1, CPU-friendly) | ogre2 (default for Gazebo Harmonic)
GZ_RENDER_ENGINE=${render_engine}
EOF

# ── Report to stdout ───────────────────────────────────────────────────────
wsl_tag=""
(( is_wsl == 1 )) && wsl_tag="  [WSL]"

gpu_line="none detected"
(( has_gpu == 1 )) && gpu_line="${gpu_name} — ${gpu_vram_gb} GB VRAM"

cat <<EOF

RAISE 2026 — hardware detection
  OS:        ${os_id} ${os_version} (${os_codename})${wsl_tag}
  Kernel:    ${kernel}
  CPU:       ${cpu_cores} cores
  RAM:       ${ram_gb} GB
  GPU:       ${gpu_line}

  ROS 2:     ${ros_distro}
  Tier:      ${tier}
  Renderer:  ${render_engine}
  VLA:       ${vla_backend}

  Wrote:     ${ENV_FILE}
EOF

# ── Friendly warnings ──────────────────────────────────────────────────────
if [[ "$os_id" != "ubuntu" ]]; then
  echo
  echo "⚠  Native install path supports Ubuntu only. Use the Docker path."
elif [[ "$ros_distro" == "jazzy" ]]; then
  echo
  echo "✓  Ubuntu 24.04 → ROS 2 Jazzy. This is the TESTED reference platform."
elif [[ "$ros_distro" == "humble" ]]; then
  echo
  echo "⚠  Ubuntu 22.04 → ROS 2 Humble. This path is UNTESTED / best-effort."
  echo "   RAISE 2026 was developed and tested on Ubuntu 24.04 + Jazzy."
  echo "   Humble uses the same Gazebo Harmonic, so the labs should work, but"
  echo "   nothing on 22.04 has been verified. If you hit trouble, the Docker"
  echo "   path (always Jazzy) is the reliable fallback."
else
  echo
  echo "⚠  Ubuntu ${os_version} has no native path (only 24.04/Jazzy and 22.04/Humble)."
  echo "   Use the Docker path instead."
fi

if (( is_wsl == 1 )); then
  echo
  echo "⚠  WSL detected. Gazebo Harmonic GUI requires WSLg (Windows 11 + recent drivers)."
  echo "   Headless mode + remote VNC also works."
fi

if (( has_gpu == 0 )) && command -v lspci >/dev/null 2>&1; then
  if lspci 2>/dev/null | grep -qiE 'vga|3d|display' \
     && ! lspci 2>/dev/null | grep -qi nvidia; then
    echo
    echo "ℹ  Non-NVIDIA GPU detected (AMD / Intel). VLA backend stays remote, but you"
    echo "   can manually set GZ_RENDER_ENGINE=ogre2 in ${ENV_FILE} if your driver supports it."
  fi
fi
